spring.application.name=homemanagementapi

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/homemanagement
#spring.datasource.username=shyamramath
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Configuration (PostgreSQL)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/homemanagement?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Dhyan1978*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration (MySQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
